version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - cpu-network

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 100M
    networks:
      - cpu-network

  db:
    image: postgres:12.12
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: kaua
      POSTGRES_DB: cpu-db
    ports:
      - "5433:5432"
    networks:
      - cpu-network
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  java-app:
    image: cpu-application:1.0
    container_name: java-app
    restart: always
    build: ./java-app
    working_dir: /java-app
    environment:
      KAFKA_URL: http://kafka:9092
      POSTGRES_URI: jdbc:postgresql://postgres-db:5432/cpu-db
      POSTGRES_USERNAME: kaua
      POSTGRES_PASSWORD: 123456
      CORS_PATTERNS: http://localhost:80,http://localhost:3000,http://localhost:8080
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    networks:
      - cpu-network
    depends_on:
      - kafka
      - zookeeper
      - db
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 100M


networks:
  cpu-network:
    driver: bridge
